FROM kartoza/postgis:17-3.5--v2025.08.23

# Instalar H3 como paquete binario para PostgreSQL 17 desde PGDG
RUN apt-get update && apt-get install -y --no-install-recommends \
      postgresql-17-h3 \
  && rm -rf /var/lib/apt/lists/*